name: Generate README
on: [push, pull_request]

jobs:
 generate-readme:
  name: Generate README
  runs-on: ubuntu-latest
  permissions:
   contents: write
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["18.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v3
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v2
     with:
      version: latest
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node }}
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Generate README
     run: pnpm run generate-docs
   - name: 📤 Commit changes
     run: |
      if [[ "$(git status --porcelain)" != "" ]]; then
      git config user.name 'GitHub Actions'
      git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      git add .

      # Sanitize the input by removing special characters and escaping double quotes
      sanitized_message=$(echo "${{ github.event.head_commit.message }}" | sed 's/[^A-Za-z0-9._-]/_/g' | sed 's/"/\\"/g')
      commit_message="${sanitized_message} | Generated README.md docs"

      git commit -m "$commit_message"
      git push -f
      fi
