name: Generate README
on: [push, pull_request]

jobs:
 generate-readme:
  name: Generate README
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v3
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v2
     with:
      version: 7
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node }}
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Generate README
     run: node src/generateDocs.mjs
   - name: 📤 Commit changes
     uses: EndBug/add-and-commit@v7
     with:
      message: ${{ github.event.head_commit.message }} | Generated README.md docs
      add: "README.md"
      author_name: "GitHub Actions"
      author_email: "41898282+github-actions[bot]@users.noreply.github.com"
      committer_name: "GitHub Actions"
      committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
      push: true
      branch: ${{ github.ref }}
